"""Regenerate `src/layout/organisms.py` from the BiGG model list.

The map picker lists models by their BiGG identifier -- iJO1366, iML1515,
iYS1720 -- which is unsearchable unless you already know which organism you
want. BiGG's `/api/v2/models` carries an `organism` field for every model, so
the identifier can be shown and searched next to the species.

The result is written as a Python module rather than JSON because `data/` and
`*.json` are both gitignored, and this table has to ship with the code: the
index is built on machines that have the repository and may not have the
network.

    python scripts/fetch_bigg_organisms.py
    python scripts/fetch_bigg_organisms.py --check   # non-zero if out of date
"""

import argparse
import json
import os
import sys
import urllib.request

API = "http://bigg.ucsd.edu/api/v2/models"
TARGET = os.path.join("src", "layout", "organisms.py")

# Common names, keyed by binomial. Curated: BiGG has no such field, and a
# reader searching the picker is far more likely to type "yeast" or "malaria"
# than "Saccharomyces" or "Plasmodium falciparum". Kept to names in ordinary
# use rather than invented ones, and every entry covers at least one model in
# the corpus.
COMMON_NAMES = {
    "Acinetobacter baumannii": "Acinetobacter",
    "Bacillus subtilis": "hay bacillus",
    "Chlamydomonas reinhardtii": "green alga",
    "Clostridioides difficile": "C. diff",
    "Clostridium ljungdahlii": "acetogen",
    "Cricetulus griseus": "Chinese hamster, CHO",
    "Escherichia coli": "E. coli",
    "Geobacter metallireducens": "Geobacter",
    "Helicobacter pylori": "H. pylori",
    "Homo sapiens": "human",
    "Klebsiella pneumoniae": "Klebsiella",
    "Lactococcus lactis": "lactic acid bacterium",
    "Methanosarcina barkeri": "methanogen",
    "Mus musculus": "mouse",
    "Mycobacterium tuberculosis": "tuberculosis",
    "Phaeodactylum tricornutum": "diatom",
    "Plasmodium berghei": "malaria parasite",
    "Plasmodium cynomolgi": "malaria parasite",
    "Plasmodium falciparum": "malaria parasite",
    "Plasmodium knowlesi": "malaria parasite",
    "Plasmodium vivax": "malaria parasite",
    "Pseudomonas putida": "Pseudomonas",
    "Saccharomyces cerevisiae": "baker's yeast",
    "Salmonella enterica": "Salmonella",
    "Salmonella pan-reactome": "Salmonella",
    "Shigella boydii": "Shigella",
    "Shigella dysenteriae": "Shigella",
    "Shigella flexneri": "Shigella",
    "Shigella sonnei": "Shigella",
    "Staphylococcus aureus": "staph",
    "Synechococcus elongatus": "cyanobacterium",
    "Synechocystis sp.": "cyanobacterium",
    "Thermotoga maritima": "thermophile",
    "Trypanosoma cruzi": "Chagas parasite",
    "Yersinia pestis": "plague bacterium",
}

HEADER = '''"""Which organism each BiGG model describes.

Generated by `scripts/fetch_bigg_organisms.py` from BiGG's model list; do not
edit by hand. `COMMON` is curated there, not supplied by BiGG.

`ORGANISM` is the strain-level name BiGG publishes. `binomial()` strips the
strain back to genus and species, which is what `COMMON` is keyed on, so a
new E. coli strain model inherits "E. coli" without another edit here.
"""

'''


def binomial_of(organism):
    """Genus and species, with the strain suffix removed."""
    if not organism:
        return ""
    parts = organism.split()
    if len(parts) >= 2 and parts[1][:1].islower():
        return " ".join(parts[:2])
    return parts[0] if parts else ""


def render_module(models):
    lines = [HEADER, "ORGANISM = {\n"]
    for m in sorted(models, key=lambda m: m["bigg_id"]):
        lines.append("    %r: %r,\n" % (m["bigg_id"], m.get("organism") or ""))
    lines.append("}\n\nCOMMON = {\n")
    for name in sorted(COMMON_NAMES):
        lines.append("    %r: %r,\n" % (name, COMMON_NAMES[name]))
    lines.append("}\n")
    lines.append('''

def binomial(organism):
    """Genus and species, with the strain suffix removed."""
    if not organism:
        return ""
    parts = organism.split()
    if len(parts) >= 2 and parts[1][:1].islower():
        return " ".join(parts[:2])
    return parts[0] if parts else ""


def describe(model_id):
    """(organism, binomial, common name) for a BiGG model id.

    Unknown models give empty strings rather than raising: the picker has to
    keep working for a model drawn from a local SBML file that BiGG has never
    heard of.
    """
    organism = ORGANISM.get(model_id, "")
    short = binomial(organism)
    return organism, short, COMMON.get(short, "")


def search_text(model_id):
    """Everything a picker search box should match on, lowercased."""
    organism, short, common = describe(model_id)
    parts = [model_id, organism, short, common]
    return " ".join(p for p in parts if p).lower()
''')
    return "".join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--target", default=TARGET)
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if the module is out of date")
    args = parser.parse_args(argv)

    with urllib.request.urlopen(API, timeout=60) as response:
        models = json.load(response)["results"]
    print("BiGG returned %d models" % len(models))

    missing = sorted({binomial_of(m.get("organism")) for m in models}
                     - set(COMMON_NAMES) - {""})
    if missing:
        print("no common name for: %s" % ", ".join(missing))

    text = render_module(models)
    old = None
    if os.path.exists(args.target):
        with open(args.target, encoding="utf-8") as handle:
            old = handle.read()
    if args.check:
        if old != text:
            print("%s is out of date" % args.target)
            return 1
        print("%s matches BiGG" % args.target)
        return 0

    with open(args.target, "w", encoding="utf-8") as handle:
        handle.write(text)
    print("wrote %s (%d organisms, %d common names)"
          % (args.target, len(models), len(COMMON_NAMES)))
    return 1 if missing else 0


if __name__ == "__main__":
    raise SystemExit(main())
