import os
import shutil
import json

SOURCE_ROOT = "data/bigg"
REPO_NAME = "escher_maps_BiGG"
REPO_ROOT = os.path.abspath(REPO_NAME)

def main():
    if not os.path.exists(REPO_ROOT):
        os.makedirs(REPO_ROOT)
        print(f"Created repo directory: {REPO_ROOT}")
        
    # Walk through data/bigg
    # Structure: data/bigg/{model_id}/*.json
    
    count = 0
    
    for item in os.listdir(SOURCE_ROOT):
        source_dir = os.path.join(SOURCE_ROOT, item)
        
        # Skip 'models' and 'test_model' source folders
        if item in ['models', 'test_model']:
            continue
            
        if os.path.isdir(source_dir):
            # This is likely a model output folder
            model_id = item
            
            # Destination folder in repo
            dest_dir = os.path.join(REPO_ROOT, model_id)
            
            # Check for JSON maps
            map_files = [f for f in os.listdir(source_dir) if f.endswith(".json")]
            
            if not map_files:
                continue
                
            if not os.path.exists(dest_dir):
                os.makedirs(dest_dir)
                
            for map_file in map_files:
                src = os.path.join(source_dir, map_file)
                dst = os.path.join(dest_dir, map_file)
                shutil.copy2(src, dst)
                print(f"Copied: {model_id}/{map_file}")
                count += 1
                
    # Create README
    readme_path = os.path.join(REPO_ROOT, "README.md")
    with open(readme_path, "w") as f:
        f.write("# Escher Maps for BiGG Models\n\n")
        f.write("This repository contains autogenerated metabolic maps for BiGG models.\n")
        f.write("Maps are decomposed into subsystems and also provided as a combined global layout.\n\n")
        f.write("## Structure\n")
        f.write("- `{Model_ID}/`\n")
        f.write("  - `{Model_ID}_Combined.json`: Global tiled map.\n")
        f.write("  - `{Model_ID}_{Subsystem}.json`: Individual subsystem map.\n")
        f.write("\n\nGenerated by AutoLayout AI (Tianyu Wu).\n")
        
    print(f"\nSuccessfully organized {count} maps into {REPO_ROOT}")

if __name__ == "__main__":
    main()
