import json
import random

def create_escher_json(nodes, reactions, text_labels=None, canvas_width=5000, canvas_height=5000, author="AutoLayout AI"):
    """
    Constructs the Escher JSON object.
    nodes: Dict of node objects (from refinement)
    reactions: Dict of reaction objects (edges need to be routed)
    text_labels: Optional dict of text label objects
    """
    if text_labels is None:
        text_labels = {}
        
    escher_map = [
        {
            "map_name": "Autogenerated Map",
            "map_id": "auto_layout_001",
            "map_description": f"Generated by {author}",
            "homepage": "https://escher.github.io",
            "schema": "https://escher.github.io/escher/jsonschema/1-0-0#"
        },
        {
            "reactions": reactions,
            "nodes": nodes,
            "text_labels": text_labels,
            "canvas": {
                "x": 0,
                "y": 0,
                "width": canvas_width,
                "height": canvas_height
            }
        }
    ]
    return escher_map

def serialize_results(graph, coords, output_path, author="AutoLayout AI", center_map=False):
    """
    Full pipeline to save graph + coords as JSON.
    """
    # 1. Convert nodes
    from src.refinement import generate_node_primitives
    escher_nodes = generate_node_primitives(graph, coords)
    
    # 2. Convert reactions (Simple segment generation)
    escher_reactions = {}
    # Iterate edges in graph, finding reaction nodes
    # In bipartite graph: Reaction Node <-> Metabolite Node
    # We need to reconstruct "Reactions" from the Reaction Nodes in the graph
    
    for n, data in graph.nodes(data=True):
        if data.get('type') == 'reaction':
            rxn_id = n
            # Find neighbors (metabolites)
            metabolites = []
            segments = {} # Escher segments (edges)
            
            # Generate Segments (Edges)
            # Connect Reaction Node to each Metabolite Node
            segment_id_counter = 0
            
            # Initialize rxn_obj first
            rxn_obj = {
                "name": data.get('name', rxn_id),
                "bigg_id": rxn_id,
                "reversibility": False, 
                "label_x": escher_nodes[rxn_id]['x'],
                "label_y": escher_nodes[rxn_id]['y'] - 40, # Offset label above node
                "gene_reaction_rule": "",
                "genes": [],
                "metabolites": [], 
                "segments": {} 
            }
            
            # Now iterate neighbors
            neighbors = list(graph.neighbors(n))
            
            for neighbor in neighbors:
                met_id = neighbor
                if met_id not in escher_nodes:
                    continue
                    
                # Create a segment from Reaction -> Metabolite (or vice versa)
                seg_id = f"{rxn_id}_s{segment_id_counter}"
                segment_id_counter += 1
                
                segment = {
                    "from_node_id": rxn_id,
                    "to_node_id": met_id,
                    "b1": None,
                    "b2": None
                }
                segments[seg_id] = segment
                
                # Also populate the 'metabolites' list
                rxn_obj['metabolites'].append({
                    "bigg_id": met_id,
                    "coefficient": 1 
                })
            
            rxn_obj["segments"] = segments
            escher_reactions[rxn_id] = rxn_obj
            
    # --- COLLISION RESOLUTION FOR LABELS ---
    # User Request: "Strict constraint... move up or down... don't overlap network"
    # We freeze nodes/edges, only move reaction labels.
    
    # 1. Build Spatial Index of Obstacles (Nodes & Edges)
    obstacles = []
    
    # Node Obstacles (Radius ~40)
    for nid, n_data in escher_nodes.items():
        obstacles.append({
            'type': 'circle',
            'x': n_data['x'],
            'y': n_data['y'],
            'r': 50 # Generous node radius
        })
        
    # Edge Obstacles (Segments)
    for rid, r_data in escher_reactions.items():
        for seg in r_data['segments'].values():
            start_node = escher_nodes[seg['from_node_id']]
            end_node = escher_nodes[seg['to_node_id']]
            obstacles.append({
                'type': 'line',
                'x1': start_node['x'], 'y1': start_node['y'],
                'x2': end_node['x'], 'y2': end_node['y'],
                'width': 20 # Edge thickness buffer
            })
            
    # Helper: Check Collision
    def is_colliding(lx, ly, width=200, height=50):
        # Label Box (assume centered at lx, ly)
        l_min_x, l_max_x = lx - width/2, lx + width/2
        l_min_y, l_max_y = ly - height/2, ly + height/2
        
        for obs in obstacles:
            if obs['type'] == 'circle':
                # Box vs Circle (Simplified to Box vs Box for speed)
                o_min_x, o_max_x = obs['x'] - obs['r'], obs['x'] + obs['r']
                o_min_y, o_max_y = obs['y'] - obs['r'], obs['y'] + obs['r']
                
                if not (l_max_x < o_min_x or l_min_x > o_max_x or l_max_y < o_min_y or l_min_y > o_max_y):
                    return True
                    
            elif obs['type'] == 'line':
                # Box vs Line Segment
                # Check if any of 4 box corners or center are close to line segment
                # Simplified: Check distance from line segment to box center
                # This is heuristic but fast.
                p1 = (obs['x1'], obs['y1'])
                p2 = (obs['x2'], obs['y2'])
                p3 = (lx, ly)
                
                # Distance from point p3 to segment p1-p2
                x1, y1 = p1
                x2, y2 = p2
                x3, y3 = p3
                
                px = x2 - x1
                py = y2 - y1
                norm = px*px + py*py
                
                u =  ((x3 - x1) * px + (y3 - y1) * py) / float(norm + 1e-9)
                
                if u > 1:
                    u = 1
                elif u < 0:
                    u = 0
                    
                x = x1 + u * px
                y = y1 + u * py
                
                dx = x - x3
                dy = y - y3
                
                dist = (dx*dx + dy*dy)**0.5
                
                # Threshold: Half height + edge width
                if dist < (height/2 + obs['width']):
                    return True
            
            elif obs['type'] == 'box':
                # Box vs Box
                o_min_x, o_max_x = obs['x'] - obs['w']/2, obs['x'] + obs['w']/2
                o_min_y, o_max_y = obs['y'] - obs['h']/2, obs['y'] + obs['h']/2
                
                if not (l_max_x < o_min_x or l_min_x > o_max_x or l_max_y < o_min_y or l_min_y > o_max_y):
                    # Overlap detected
                    return True
                    
        return False

    # 2. Resolve Labels
    for rid, r_data in escher_reactions.items():
        base_x = r_data['label_x']
        base_y = r_data['label_y']
        
        # Estimate label width
        # Approx 20px per char + padding
        name_len = len(r_data.get('name', str(rid)))
        label_width = max(150, name_len * 22)  
        label_height = 50 # Height is roughly constant
        
        # Candidate positions: [Current, Up, Down, More Up, More Down...]
        # Steps of 60px
        candidates = [0, -60, 60, -120, 120, -180, 180, -240, 240]
        
        best_y = base_y
        found_clean = False
        
        for offset in candidates:
            test_y = base_y + offset
            if not is_colliding(base_x, test_y, width=label_width, height=label_height):
                best_y = test_y
                found_clean = True
                break
        
        # Update Position
        r_data['label_y'] = best_y
        
        # Add finalized label to obstacles relative to preventing other labels from overlapping it?
        # Use a box obstacle for the label
        obstacles.append({
            'type': 'box', # Treat label as a box obstacle now
            'x': base_x,
            'y': best_y,
            'w': label_width,
            'h': label_height
        })

    # 3. Calculate Canvas Bounds
    if escher_nodes:
        # Re-calc bounds with potentially new label positions? 
        # Labels are usually inside the bounding box of nodes anyway.
        xs = [n['x'] for n in escher_nodes.values()]
        ys = [n['y'] for n in escher_nodes.values()]
        
        # Calculate content dimensions (not absolute positions)
        min_x, max_x = min(xs), max(xs)
        min_y, max_y = min(ys), max(ys)
        
        content_width = max_x - min_x
        content_height = max_y - min_y
        
        # Canvas should be content size + padding on both sides
        padding = 500
        width = content_width + 2 * padding
        height = content_height + 2 * padding
        
        # --- SHIFT COORDS TO CENTER/TRIM (Optional) ---
        if center_map:
            # We want min_x to land at padding, min_y to land at padding
            shift_x = padding - min_x
            shift_y = padding - min_y
            
            # Apply Shift to all Nodes
            for nid, n_data in escher_nodes.items():
                n_data['x'] += shift_x
                n_data['y'] += shift_y
                if 'label_x' in n_data:
                    n_data['label_x'] += shift_x
                if 'label_y' in n_data:
                    n_data['label_y'] += shift_y
                
            # Apply Shift to all Reactions (label_x, label_y)
            for rid, r_data in escher_reactions.items():
                r_data['label_x'] += shift_x
                r_data['label_y'] += shift_y
                
            # Update bounds (now they start at padding)
            min_x += shift_x; max_x += shift_x
            min_y += shift_y; max_y += shift_y
        
        # Create Text Label for Attribution
        # Position: Top-Right of content, slightly above
        label_x = max_x - 1000
        label_y = min_y - 200
        
        text_labels = {
            "attribution_label": {
                "x": label_x,
                "y": label_y,
                "text": f"Created by {author}",
                "rotation": 0, 
                "scale": 5.0 # Large text
            }
        }
        
    else:
        width, height = 5000, 5000
        text_labels = {}

    # 4. Save
    data = create_escher_json(escher_nodes, escher_reactions, text_labels=text_labels, canvas_width=width, canvas_height=height, author=author)
    with open(output_path, 'w') as f:
        json.dump(data, f, indent=2)
    print(f"Saved Escher map to {output_path}")

